env:
  commonjs: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
plugins:
  - "@typescript-eslint"
rules: {
  no-console: 0,
  no-empty: 0,
  no-irregular-whitespace: 1
}
